"use client";

import { SponsorNav } from "@/components/sponsor/sponsor-nav";
import { SponsorDataTable } from "@/components/sponsor/sponsor-data-table";
import { csvFields } from "@/components/dashboards/dashboards/participants";
import { columns } from "./resume-book-columns";

interface SponsorResumeBookPageProps {
  tenant: string;
}

const dummyData = [
  {
    _id: 1,
    firstname: "Alice",
    lastname: "Johnson",
    email: "alice@example.com",
    telephone: "+1 (555) 123-4567",
    discord: "alice#1234",
    major: "Computer Science",
    age: "21",
    country: "United States",
    school: "University of California, Riverside",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "M",
    dietrestriction: "None",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/alice-johnson.pdf",
  },
  {
    _id: 2,
    firstname: "Bob",
    lastname: "Smith",
    email: "bob@example.com",
    telephone: "+1 (555) 234-5678",
    discord: "bob#5678",
    major: "Computer Engineering",
    age: "20",
    country: "United States",
    school: "California State University, Fullerton",
    grade: "Undergraduate",
    gender: "Male",
    shirt: "L",
    dietrestriction: "Vegetarian",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/bob-smith.pdf",
  },
  {
    _id: 3,
    firstname: "Carol",
    lastname: "Martinez",
    email: "carol@example.com",
    telephone: "+1 (555) 345-6789",
    discord: "carol_m",
    major: "Design and Media Arts",
    age: "22",
    country: "United States",
    school: "University of California, Los Angeles",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "S",
    dietrestriction: "Vegan",
    status: "PENDING",
    terms: true,
    mlh: false,
  },
  {
    _id: 4,
    firstname: "David",
    lastname: "Kim",
    email: "david@example.com",
    telephone: "+1 (555) 456-7890",
    discord: "davidk",
    major: "Data Science",
    age: "23+",
    country: "United States",
    school: "University of California, San Diego",
    grade: "Graduate (Masters, Doctoral, etc)",
    gender: "Male",
    shirt: "XL",
    dietrestriction: "None",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/david-kim.pdf",
  },
  {
    _id: 5,
    firstname: "Eva",
    lastname: "Chen",
    email: "eva@example.com",
    telephone: "+1 (555) 567-8901",
    discord: "eva_chen",
    major: "Computer Science",
    age: "19",
    country: "United States",
    school: "Stanford University",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "S",
    dietrestriction: "Gluten-Free",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/eva-chen.pdf",
  },
  {
    _id: 6,
    firstname: "Frank",
    lastname: "Thompson",
    email: "frank@example.com",
    telephone: "+1 (555) 678-9012",
    discord: "frank_t",
    major: "Computer Science",
    age: "20",
    country: "United States",
    school: "University of Southern California",
    grade: "Undergraduate",
    gender: "Male",
    shirt: "L",
    dietrestriction: "None",
    status: "ACCEPTANCE",
    terms: true,
    mlh: false,
  },
  {
    _id: 7,
    firstname: "Grace",
    lastname: "Liu",
    email: "grace@example.com",
    telephone: "+1 (555) 789-0123",
    discord: "grace_liu",
    major: "Computer Science",
    age: "21",
    country: "United States",
    school: "University of California, Irvine",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "M",
    dietrestriction: "Halal",
    status: "PENDING",
    terms: true,
    mlh: true,
  },
  {
    _id: 8,
    firstname: "Henry",
    lastname: "Davis",
    email: "henry@example.com",
    telephone: "+1 (555) 890-1234",
    discord: "henry_d",
    major: "Software Engineering",
    age: "23+",
    country: "United States",
    school: "California Polytechnic State University",
    grade: "Graduate (Masters, Doctoral, etc)",
    gender: "Male",
    shirt: "XXL",
    dietrestriction: "Dairy-Free",
    status: "REJECTION",
    terms: true,
    mlh: false,
  },
  {
    _id: 9,
    firstname: "Isabella",
    lastname: "Garcia",
    email: "isabella@example.com",
    telephone: "+1 (555) 901-2345",
    discord: "isa_garcia",
    major: "Computer Science",
    age: "22",
    country: "United States",
    school: "University of California, Berkeley",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "M",
    dietrestriction: "None",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/isabella-garcia.pdf",
  },
  {
    _id: 10,
    firstname: "James",
    lastname: "Wilson",
    email: "james@example.com",
    telephone: "+1 (555) 012-3456",
    discord: "james_w",
    major: "Computer Science",
    age: "20",
    country: "United States",
    school: "University of California, Santa Barbara",
    grade: "Undergraduate",
    gender: "Male",
    shirt: "L",
    dietrestriction: "None",
    status: "PENDING",
    terms: true,
    mlh: true,
  },
  {
    _id: 11,
    firstname: "Katherine",
    lastname: "Brown",
    email: "katherine@example.com",
    telephone: "+1 (555) 111-2222",
    discord: "kat_brown",
    major: "Data Science",
    age: "21",
    country: "United States",
    school: "University of California, Davis",
    grade: "Undergraduate",
    gender: "Female",
    shirt: "S",
    dietrestriction: "Vegetarian",
    status: "ACCEPTANCE",
    terms: true,
    mlh: true,
    resume: "https://example.com/resumes/katherine-brown.pdf",
  },
  {
    _id: 12,
    firstname: "Liam",
    lastname: "Nguyen",
    email: "liam@example.com",
    telephone: "+1 (555) 333-4444",
    discord: "liam_nguyen",
    major: "Computer Engineering",
    age: "19",
    country: "United States",
    school: "San Jose State University",
    grade: "Undergraduate",
    gender: "Male",
    shirt: "M",
    dietrestriction: "None",
    status: "ACCEPTANCE",
    terms: true,
    mlh: false,
  },
];

export function ResumeBookPage({ tenant }: SponsorResumeBookPageProps) {
  return (
    <div className="mx-auto max-w-6xl space-y-6 px-4 py-6 md:py-10">
      <SponsorNav tenant={tenant} />

      <div className="flex flex-col gap-1">
        <h1 className="text-2xl font-bold">Resume Book</h1>
        <p className="text-sm text-muted-foreground">
          Browse participant profiles, resumes, and contact information.
        </p>
      </div>

      <SponsorDataTable
        data={dummyData}
        columns={columns}
        csvFields={csvFields}
      />
    </div>
  );
}
